### PR TITLE
Add a template document for iOS app icon design

### PR DESCRIPTION
**Pull request by FradSer**
:-)
Maybe useful.

### CODE REVIEW

**Comment by jamztang** [comment]
Thanks @FradSer, it's useful but I think we should move it to somewhere else instead of committing to the main repository. I am trying to work out with a resource section in the webpage, what do you think if I put it there or in the wiki section for now?

**Comment by FradSer** [comment]
Of course, if you like.

**Comment by jamztang** [comment]
Hey Fred, sorry for hanging I am into something else, I will be getting back into this and make sure you get properly attributed. I would also like to talk with you a bit more on future roadmap, do you want to continue and discuss in email?

**Comment by FradSer** [comment]
No problem, if you want we can discuss in email. Mail me to this address: fradser@gmail.com.

**Pull request closed without merging**
